backend:
  name: git-gateway
  repo: lsu-ddem/pathways-engineering
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: 
    - admin 
    - editor 

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  # Unit 1 
  - name: "Unit 1 - Lesson 1" 
    label: "Unit 1 - Lesson 1" 
    folder: "content/1_Unit_1/1_Lesson_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Unit 1 - Lesson 2" 
    label: "Unit 1 - Lesson 2" 
    folder: "content/1_Unit_1/2_Lesson_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    

  #Projects     
  - name: "Unit 1 - Lesson 2 - Project 1" 
    label: "Unit 1 - Lesson 2 - Project 1" 
    folder: "content/1_Unit_1/2_Lesson_2/1_Project_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "Unit 1 - Lesson 2 - Project 2" 
    label: "Unit 1 - Lesson 2 - Project 2" 
    folder: "content/1_Unit_1/2_Lesson_2/2_Project_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "Unit 1 - Lesson 2 - Project 3" 
    label: "Unit 1 - Lesson 2 - Project 3" 
    folder: "content/1_Unit_1/2_Lesson_2/3_Project_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}             
  
  #Back to lessons 
  - name: "Unit 1 - Lesson 3" 
    label: "Unit 1 - Lesson 3" 
    folder: "content/1_Unit_1/3_Lesson_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}     
  
  #####     
  # Unit 2
  - name: "Unit 2 - Lesson 1" 
    label: "Unit 2 - Lesson 1" 
    folder: "content/2_Unit_2/1_Lesson_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Unit 2 - Lesson 2" 
    label: "Unit 2 - Lesson 2" 
    folder: "content/2_Unit_2/2_Lesson_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    

  #Projects     
  - name: "Unit 2 - Lesson 2 - Project 1" 
    label: "Unit 2 - Lesson 2 - Project 1" 
    folder: "content/2_Unit_2/2_Lesson_2/1_Project_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "Unit 2 - Lesson 2 - Project 2" 
    label: "Unit 2 - Lesson 2 - Project 2" 
    folder: "content/2_Unit_2/2_Lesson_2/2_Project_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}        
  
  #Back to lessons 
  - name: "Unit 2 - Lesson 3" 
    label: "Unit 2 - Lesson 3" 
    folder: "content/2_Unit_2/3_Lesson_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}     
###
# Unit 3
  - name: "Unit 3 - Lesson 1" 
    label: "Unit 3 - Lesson 1" 
    folder: "content/3_Unit_3/1_Lesson_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Unit 3 - Lesson 2" 
    label: "Unit 3 - Lesson 2" 
    folder: "content/3_Unit_3/2_Lesson_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    

  #Projects     
  - name: "Unit 3 - Lesson 2 - Project 1" 
    label: "Unit 3 - Lesson 2 - Project 1" 
    folder: "content/3_Unit_3/2_Lesson_2/1_Project_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "Unit 3 - Lesson 2 - Project 2" 
    label: "Unit 3 - Lesson 2 - Project 2" 
    folder: "content/3_Unit_3/2_Lesson_2/2_Project_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "Unit 3 - Lesson 2 - Project 3" 
    label: "Unit 3 - Lesson 2 - Project 3" 
    folder: "content/3_Unit_3/2_Lesson_2/3_Project_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}       
  - name: "Unit 3 - Lesson 2 - Project 4" 
    label: "Unit 3 - Lesson 2 - Project 4" 
    folder: "content/3_Unit_3/2_Lesson_2/4_Project_4" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}          
  
  #Back to lessons 
  - name: "Unit 3 - Lesson 3" 
    label: "Unit 3 - Lesson 3" 
    folder: "content/3_Unit_3/3_Lesson_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}     
  
  #####     
  # Unit 4
  # biological engineering 
  - name: "Unit 4 - Lesson 1" 
    label: "Unit 4 - Lesson 1" 
    folder: "content/4_Unit_4/biological-engineering/1_Lesson_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Unit 4 - Lesson 2" 
    label: "Unit 4 - Lesson 2" 
    folder: "content/4_Unit_4/biological-engineering/2_Lesson_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    

  #Projects     
  - name: "Unit 4 - Lesson 2 - Project 1" 
    label: "Unit 4 - Lesson 2 - Project 1" 
    folder: "content/4_Unit_4/biological-engineering/2_Lesson_2/1_Project_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "Unit 4 - Lesson 2 - Project 2" 
    label: "Unit 4 - Lesson 2 - Project 2" 
    folder: "content/4_Unit_4/biological-engineering/2_Lesson_2/2_Project_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "Unit 4 - Lesson 2 - Project 3" 
    label: "Unit 4 - Lesson 2 - Project 3" 
    folder: "content/4_Unit_4/biological-engineering/2_Lesson_2/3_Project_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}       
  - name: "Unit 4 - Lesson 2 - Project 4" 
    label: "Unit 4 - Lesson 2 - Project 4" 
    folder: "content/4_Unit_4/biological-engineering/2_Lesson_2/4_Project_4" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}          
  
  #Back to lessons 
  - name: "Unit 4 - Lesson 3" 
    label: "Unit 4 - Lesson 3" 
    folder: "content/4_Unit_4/biological-engineering/3_Lesson_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}   
