backend:
  name: git-gateway
  repo: lsu-ddem/pathways-engineering
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: 
    - admin 
    - editor 

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "Unit 1 - Lesson 1" 
    label: "Unit 1 - Lesson 1" 
    folder: "content/1_Unit_1/1_Lesson_1" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Unit 2 - Lesson 2" 
    label: "Unit 2 - Lesson 2" 
    folder: "content/1_Unit_1/2_Lesson_2" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "Unit 3 - Lesson 3" 
    label: "Unit 3 - Lesson 3" 
    folder: "content/1_Unit_1/2_Lesson_3" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}     
  